#+title: README
#+author: Étienne Deparis

Chwall [[https://en.wiktionary.org/wiki/Appendix:French_pronunciation][{ʃwal}]] is tiny automatic wallpaper changer, written in python.

It's name is the contraction of /change wallpaper/, which may be
pronounced as a twisted version of /cheval/, which means /horse/ in
french.

* Goal and features

Easily change your wallpaper from time to time, benefiting from various
online sources and your own wallpapers collections.

Chwall is currently able to retrieve pictures from the following
sources:

- your local folders
- bing pictures of the day
- National Geographic pictures of the day
- NASA astronomical pictures of the day
- deviantart RSS feeds
- Unsplash random API (requires a free account to access their API)
- Reddit
- Smashing Magazine monthly wallpaper collection

* Install

** Locally in a virtualenv

#+begin_src shell
pip install -r requirements.txt
python setup.py install
#+end_src

** System-wide

#+begin_src shell
sudo make install
#+end_src

There is also two AUR packages for archlinux:
- [[https://aur.archlinux.org/packages/chwall][chwall]] (stable version)
- [[https://aur.archlinux.org/packages/chwall-git][chwall-git]] (unstable version)

* Usage

Chwall is organized around 4 components:

- chwall-app
- chwall-icon
- chwall
- chwall-daemon

The ~chwall-app~ and ~chwall-icon~ are alternative graphical interface
to the simple ~chwall~ command line client. These 3 programs are here to
drive the ~chwall-daemon~ component, which is responsible to change the
wallpaper at given interval of time.

After a system-wide installation, you should find a icon among your
other programs, which starts ~chwall-app~. From there, you'll be able to
access the preferences window to customize the behavior of chwall.

You can also interact with the daemon through the system tray icon
~chwall-icon~, which also let you customize Chwall with the preferences
window.

In the case, where you want a totally headless experience, you should
try the simple ~chwall~ command line client. If you don't want (or
cannot) use the preferences window, you should read the [[./CONFIG.org][configuration
help]] document to know more about the chwall config file.

* Contributing

** Translations

#+html: <a href="https://translations.umaneti.net/engage/chwall/?utm_source=widget">
#+html: <img src="https://translations.umaneti.net/widgets/chwall/-/svg-badge.svg" alt="Translations state" />
#+html: </a>

Chwall is [[https://translations.umaneti.net/engage/chwall/][being translated using Weblate]], a web tool designed to ease
translating for both developers and translators.

You can also fetch the gettext files directly from the source code tree
and send your changes as a pull request (see bellow).

** Code

The canonical repository is located at
[[https://git.deparis.io/chwall]]. Mirror exists on [[https://framagit.org/milouse/chwall][Framagit]] and on [[https://github.com/milouse/chwall][Github]].

Merge request and issues are accepted on all mirrors or by mail to the
main author.

* Credits

The icon is resized [[https://openclipart.org/detail/21282/waved-horse-spring-version-2009][from the work of Bernd Wachtmeister (Touchstone)]].
